language: java
branches:
  only:
    - develop
    - /^release-[0-999].[0-999]$/
    - master
notifications:
  email:
    recipients:
      - j.bernal@upm.es
# services:
# - mysql
# - mongodb
# before_install:
# - mysql -e 'CREATE DATABASE IF NOT EXISTS forge;'
script:
  #Test unitario y de integracion con cobertura
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify

  #SONARCLOUD
  - mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=miw-upm-github -Dsonar.login=$SONAR

#Deploy https://iwvg-ecosystem.herokuapp.com/api
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU
  on:
    branch: master
#  app: iwvg-ecosystem, por defecto, nombre del artefacto