name: CD - Heroku
on:
  push:
    branches: [master1]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: {fetch-depth: 0}
      - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
        with:
          heroku_email: "j.bernal@upm.es"
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "iwvg-devops" #Must be unique in Heroku
